// Source hardening: self-host the brand fonts so they load with zero network at
// capture time and cover Turkish glyphs (latin-ext subset).
//
// We ask Google Fonts (with a modern desktop User-Agent) for the SAME css2 URL the
// stylesheet already uses. Google replies with one @font-face per (weight, subset),
// each carrying a `unicode-range` — including `latin-ext`, which holds İ Ğ Ş Ç Ö Ü ı.
// We download every referenced .woff2, rewrite the url()s to local paths (preserving
// every unicode-range), write fonts.css, and swap the CDN @import in
// colors_and_type.css to `@import url('fonts.css')`. Reversible (.orig backup) and
// idempotent (skips existing files / an already-swapped @import).

import fs from 'node:fs/promises';
import path from 'node:path';

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';

const CSS_FILE = 'colors_and_type.css';
const FONTS_CSS = 'fonts.css';
const FONTS_DIR = 'fonts';

const GOOGLE_IMPORT_RE =
  /@import\s+url\(['"]?(https:\/\/fonts\.googleapis\.com\/css2[^)'"]+)['"]?\)\s*;/;

// Only ever download font binaries from Google's font CDN — never an arbitrary host
// that happens to appear in the CSS (defends against a tampered/attacker-supplied
// stylesheet turning this fetch into an SSRF).
const ALLOWED_FONT_HOSTS = new Set(['fonts.gstatic.com', 'fonts.googleapis.com']);

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

async function exists(p) {
  try { await fs.access(p); return true; } catch { return false; }
}

/**
 * Download + self-host fonts for a campaign directory.
 * @param {string} root absolute path to the design root (holds colors_and_type.css)
 * @param {(msg:string)=>void} [log] progress sink (defaults to console.log)
 */
export async function selfHostFonts(root, log = console.log) {
  const cssPath = path.join(root, CSS_FILE);
  const origPath = `${cssPath}.orig`;
  const fontsDir = path.join(root, FONTS_DIR);

  // Prefer the pristine .orig (so re-runs still find the Google URL after a swap).
  const sourceForUrl = (await exists(origPath)) ? origPath : cssPath;
  const sourceCss = await fs.readFile(sourceForUrl, 'utf8');
  const m = sourceCss.match(GOOGLE_IMPORT_RE);

  if (!m && (await exists(path.join(root, FONTS_CSS)))) {
    log('  fonts: already self-hosted (no Google @import found) — skipping.');
    return;
  }
  if (!m) throw new Error(`Could not find a Google Fonts @import in ${sourceForUrl}`);

  const cssUrl = m[1];
  log(`  fonts: fetching face declarations from Google…`);
  const res = await fetch(cssUrl, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`Google Fonts CSS fetch failed: ${res.status}`);
  const remoteCss = await res.text();

  await fs.mkdir(fontsDir, { recursive: true });

  // Each face is preceded by a `/* subset */` comment. Capture comment + block.
  const blockRe = /\/\*\s*([^*]+?)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  const localBlocks = [];
  let downloaded = 0, reused = 0, count = 0;

  for (const match of remoteCss.matchAll(blockRe)) {
    count++;
    const subset = slug(match[1]) || `s${count}`;
    const block = match[2];

    const family = (block.match(/font-family:\s*'([^']+)'/) || [])[1] || 'font';
    const weight = (block.match(/font-weight:\s*([^;]+);/) || [])[1]?.trim().replace(/\s+/g, '_') || '400';
    const style = (block.match(/font-style:\s*([^;]+);/) || [])[1]?.trim() || 'normal';
    const urlMatch = block.match(/url\((https:\/\/[^)]+\.woff2)\)/);
    if (!urlMatch) continue;
    const remoteUrl = urlMatch[1];
    let remoteHost; try { remoteHost = new URL(remoteUrl).hostname; } catch { continue; }
    if (!ALLOWED_FONT_HOSTS.has(remoteHost)) { log(`  fonts: skipped non-Google font URL ${remoteUrl}`); continue; }

    const fileName = `${slug(family)}-${weight}-${style}-${subset}.woff2`;
    const filePath = path.join(fontsDir, fileName);

    if (await exists(filePath)) {
      reused++;
    } else {
      const fontRes = await fetch(remoteUrl, { headers: { 'User-Agent': UA } });
      if (!fontRes.ok) throw new Error(`Font download failed (${fontRes.status}): ${remoteUrl}`);
      await fs.writeFile(filePath, Buffer.from(await fontRes.arrayBuffer()));
      downloaded++;
    }

    // Keep the whole block (font-display, unicode-range, etc.); swap only the URL.
    localBlocks.push(`/* ${subset} */\n${block.replace(remoteUrl, `${FONTS_DIR}/${fileName}`)}`);
  }

  if (!localBlocks.length) throw new Error('No @font-face blocks parsed from Google CSS.');

  const header =
    `/* Self-hosted brand fonts — generated by Claude Design Exporter.\n` +
    `   Do not edit by hand; regenerate with: node export.mjs prepare\n` +
    `   unicode-range (incl. latin-ext) preserved so Turkish glyphs render. */\n\n`;
  await fs.writeFile(path.join(root, FONTS_CSS), header + localBlocks.join('\n\n') + '\n');
  log(`  fonts: ${count} faces (${downloaded} downloaded, ${reused} cached) → ${FONTS_CSS}`);

  // Swap the CDN @import to the local one (backing up the original once).
  if (GOOGLE_IMPORT_RE.test(await fs.readFile(cssPath, 'utf8'))) {
    if (!(await exists(origPath))) await fs.copyFile(cssPath, origPath);
    const current = await fs.readFile(cssPath, 'utf8');
    await fs.writeFile(cssPath, current.replace(GOOGLE_IMPORT_RE, `@import url('${FONTS_CSS}');`));
    log(`  fonts: ${CSS_FILE} now imports ${FONTS_CSS} (original → ${path.basename(origPath)})`);
  } else {
    log(`  fonts: ${CSS_FILE} already points at ${FONTS_CSS} — no swap needed.`);
  }
}
